#! /bin/bash
sed -i 's|p910nd - Printer server|Printer Server|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-p910nd/luasrc/controller/p910nd.lua
sed -i 's|p910nd - Printer server|Printer Server|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-p910nd/luasrc/model/cbi/p910nd.lua
sed -i 's|First you have to install the packages to get support for USB (kmod-usb-printer) or parallel port (kmod-lp).|p910nd Printer Server is a small non-spooling printer daemon intended for disk-less workstations.|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-p910nd/luasrc/model/cbi/p910nd.lua
sed -i 's|translate("enable")|translate("Enable")|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-p910nd/luasrc/model/cbi/p910nd.lua
sed -i 's|_("hd-idle"),|_("HD-Idle"),|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-hd-idle/luasrc/controller/hd_idle.lua
sed -i 's|hd-idle is a utility program|HD-Idle is a utility program|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-hd-idle/luasrc/model/cbi/hd_idle.lua
sed -i 's|Map("hd-idle", "hd-idle"|Map("hd-idle", "HD-Idle"|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-hd-idle/luasrc/model/cbi/hd_idle.lua
sed -i 's|_("UPNP")|_("UPnP")|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/applications/luci-upnp/luasrc/controller/upnp.lua
sed -i 's|height: 1em;|height: 2em;|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/themes/bootstrap/htdocs/luci-static/bootstrap/cascade.css
sed -i 's|height: 1em;|height: 2em;|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/luci-0.11+svn9868/themes/bootstrap/dist/www/luci-static/bootstrap/cascade.css
sed -i 's|height: 1em;|height: 2em;|g' $HOME/openwrt/TL-WR1043ND/attitude_adjustment/build_dir/target-mips_r2_uClibc-0.9.33.2/root-ar71xx/www/luci-static/bootstrap/cascade.css
